### ISSUE TITLE
Crashes on Load under VS 2015

### ISSUE THREAD

**Issue by i-e-b** [nickgravgaard/AlwaysAlignedVS#4]
Using release https://github.com/nickgravgaard/AlwaysAlignedVS/releases/tag/2017.0.0
I assume that VisualStudio 2015 isn't supported, but it's not mentioned in the docs.

This extension works like a charm on VS2017, but under 2015 it shows this error on start-up:

```
CreateInstance failed for package [AlwaysAlignedPackage]Source: 'mscorlib' Description: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified
File name: 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
```

**Comment by DanTalash** [comment]
I get exactly the same issue, and the same message shows up in my `ActivityLog.xml`.

**Comment by EtaoinWu** [comment]
According to the author, this release version was build for VS2017.

**Comment by DanTalash** [comment]
Well that would explain it. Maybe the extension should not be installable under VS2015.

**Comment by runkelz** [comment]
Same here. Could be explained please.

**Comment by R2D221** [comment]
Is there a way to convert it to VS2015?
